FACTOR_KM_AUTO = 0.1445
FACTOR_KM_MOTO = 0.114
FACTOR_KM_COLECT_DIE = 0.098


#ELECTRODOMESTICOS
FACTOR_TELEVISOR_LED = 0.007
FACTOR_AIRE_ACONDICIONADO = 0.167
FACTOR_VENTILADOR = 0.004
FACTOR_HELADERA = 0.01
FACTOR_LAVARROPA = 0.027
FACTOR_PLANCHA = 0.08
FACTOR_HORNO_ELECT = 0.133
FACTOR_MICROONDAS= 0.08


#ALIMENTOS

FACTOR_CARNE_VACA = 13.3
FACTOR_CARNE_CERDO = 4.4
FACTOR_POLLO = 6.9
FACTOR_PESCADO = 3.7
FACTOR_HUEVOS = 0.87
FACTOR_LECHE = 1.3
FACTOR_QUESO = 8.9
FACTOR_ARROZ = 0.6
FACTOR_PAN =0.48
FACTOR_PAPA = 	0.2

FACTORES = [FACTOR_KM_AUTO,
            FACTOR_KM_MOTO,
            FACTOR_KM_COLECT_DIE,
            FACTOR_TELEVISOR_LED,
FACTOR_AIRE_ACONDICIONADO,
FACTOR_VENTILADOR,
FACTOR_HELADERA,
FACTOR_LAVARROPA,
FACTOR_PLANCHA,
FACTOR_HORNO_ELECT,
FACTOR_MICROONDAS,
FACTOR_CARNE_VACA,
FACTOR_CARNE_CERDO,
FACTOR_POLLO,
FACTOR_PESCADO,
FACTOR_HUEVOS,
FACTOR_LECHE,
FACTOR_QUESO,
FACTOR_ARROZ,
FACTOR_PAN,
FACTOR_PAPA 
]
