[theme]
primaryColor="#F63366"
backgroundColor="#DDFBE0"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

#Datos Originales tema claro NO TOCAR
#[theme]
#primaryColor="#F63366"
#backgroundColor="#FFFFFF"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#262730"
#font="sans serif"